# Generated by Django 4.0.3 on 2022-03-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_alter_post_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/profile/'),
        ),
    ]
